{
 "title": "Gateway Metrics",
 "tags": [
  "yantrago",
  "gateway"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TCP Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tcp_active_connections", "legendFormat": "Concox" },
    { "expr": "fencing_tcp_active_connections", "legendFormat": "Fencing" }
   ]
  },
  {
   "title": "TCP Packets Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(tcp_packets_processed_total[1m])",
     "legendFormat": "Concox"
    },
    {
     "expr": "rate(fencing_tcp_packets_processed_total[1m])",
     "legendFormat": "Fencing"
    }
   ]
  },
  {
   "title": "Gateway JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"gateway\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}